<a href="https://colab.research.google.com/github/kaushik0212/machine-learning-/blob/main/exp%2010.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score

# Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# Naive Bayes Model
nb = GaussianNB()
nb.fit(X_train, y_train)

# Prediction
y_pred = nb.predict(X_test)

# Results
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nAccuracy:", accuracy_score(y_test, y_pred))

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Accuracy: 1.0


In [2]:
import numpy as np
from sklearn.mixture import GaussianMixture

# Sample dataset
X = np.array([
    [1, 2],
    [1.5, 1.8],
    [5, 8],
    [8, 8],
    [1, 0.6],
    [9, 11]
])

# Gaussian Mixture Model
gmm = GaussianMixture(n_components=2, random_state=42)

# Train model
gmm.fit(X)

# Predict clusters
labels = gmm.predict(X)

print("Data Points:")
print(X)

print("\nCluster Labels:")
print(labels)

Data Points:
[[ 1.   2. ]
 [ 1.5  1.8]
 [ 5.   8. ]
 [ 8.   8. ]
 [ 1.   0.6]
 [ 9.  11. ]]

Cluster Labels:
[1 1 0 0 1 0]
